fileVersion: 1
id: "9"
mappingDefinitions:
  SRC:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  SRC2:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCDS_SF10TCL
  TARGET:
    database: PRATIK
    schema: WORKPROD
  TEST:
    database: PRATIK
    schema: WORKDEV
name: Production
type: Environment
