fileVersion: 1
id: "3"
mappingDefinitions:
  TEST_SRC:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  TEST_TARGET:
    database: PRACTICE
    schema: WORKPROD
name: Production
type: Environment
