@id("fa780841-bcce-49a0-8ec5-9b79194f94c3")
@nodeType("B-N-T-SQL-2-0-0:::707")
SELECT
     "DIM_LOCATION_KEY" AS "DIM_LOCATION_KEY",
     "MARKET_SEGMENT_SUMMARY" AS "MARKET_SEGMENT_SUMMARY",
     "NATIONAL_ACCOUNT" AS "NATIONAL_ACCOUNT"
FROM {{ ref('TARGET', 'DIM_LOCATION') }} "DIM_LOCATION"