name: Coalesce Refresh
on:
  push:
    branches: [ main ]

jobs:
  coalesce-refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Coalesce CLI
        run: npm install -g @coalesce/coa

      - name: Refresh Environment
        env:
          COA_CONFIG: ${{ secrets.COA_CONFIG }}
        # Triggers a specific job or environment refresh in Coalesce
        run: coa refresh --environmentID 8 --jobID 4
