name: Deploy to PROD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  refresh-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Coalesce CLI
        run: npm install -g @coalescesoftware/coa

      - name: Write Coalesce config
        run: |
          echo '${{ secrets.COA_CONFIG }}' > coa-config.json

      - name: Create Deployment Plan
        run: npx coa plan --config coa-config.json --out ./coa-plan2 --debug

      - name: Print version
        run: npx coa --version

      - name: Trigger Coalesce Job
        run: npx coa refresh --config coa-config.json

      - name: Deploy Plan
        run: npx coa deploy --config coa-config.json --plan ./coa-plan2 --debug
